version: 2
updates:

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "type/build"
      - "scope/dockerfile"
