upstream: env TARGET=upstream docker-gen -watch /app/nginx.tmpl /etc/nginx/conf.d/10-upstream.conf
dockergen: env TARGET=server docker-gen -watch -notify "nginx -s reload" /app/nginx.tmpl /etc/nginx/conf.d/default.conf
nginx: nginx -g "daemon off;"
